name: mygoodtrip
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sqflite: ^2.0.3
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  flutter_slidable: ^0.6.0
  mask_text_input_formatter: ^2.4.0
  easy_mask: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/intro/
